DEFAULT_LLM_MODEL = "mlx-community/Qwen3.5-9B-4bit"
DEFAULT_LLM_FAST_MODEL = "mlx-community/Qwen3.5-4B-4bit"
DEFAULT_TTS_MODEL = "mlx-community/Kokoro-82M-bf16"
DEFAULT_TTS_VIBEVOICE_MODEL = "mlx-community/VibeVoice-Realtime-0.5B-fp16"
DEFAULT_TTS_CLONE_MODEL = "mlx-community/Qwen3-TTS-12Hz-1.7B-Base-4bit"
DEFAULT_STT_MODEL = "mlx-community/Qwen3-ASR-0.6B-8bit"
DEFAULT_VLM_MODEL = "mlx-community/Qwen2.5-VL-3B-Instruct-8bit"
DEFAULT_S2S_REPO = "nvidia/personaplex-7b-v1"       # auxiliary files: config, tokenizer, mimi, voices
DEFAULT_S2S_MODEL_REPO = "aufklarer/PersonaPlex-7B-MLX-4bit"  # MLX-optimized weights
